export const FETCH_URL_LIST_REQUEST = 'FETCH_URL_LIST_REQUEST'
export const FETCH_URL_LIST_SUCCESS = 'FETCH_URL_LIST_SUCCESS'
export const FETCH_URL_LIST_FAIL = 'FETCH_URL_LIST_FAIL'


export const FETCH_LIST_FILES_REQUEST = 'FETCH_LIST_FILES_REQUEST'
export const FETCH_LIST_FILES_SUCCESS = 'FETCH_LIST_FILES_SUCCESS'
export const FETCH_LIST_FILES_FAIL = 'FETCH_LIST_FILES_FAIL'

export const SAVE_USER_ID = 'SAVE_USER_ID'